import { Inter } from "next/font/google";
import "./globals.css";
import TopBar from "@/Components/commons/TopBar";
import Footer from "@/Components/commons/Footer";
import { Toaster } from "react-hot-toast";
import Navbar from "@/Components/commons/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Maldo E-Pharma",
  description: "Generated by Yohannes Lemma using Next.js and Tailwind CSS",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Toaster />
        {/* <TopBar /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
